<<<<<<< HEAD
spring:
  application:
    name: "auth-service"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://localhost:8088"


#sporing :
#   application:
#     name: SECURITY_SERVICE
#
#
#eureka :
#  client :
#    service_url : http://localhost:8761/eureka/
#
#server:
#  port : 9090
=======
server:
  port: 9296
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sreejith-a-nair/cloud-config
          clone-on-start: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


#server:
#  port: 9296
#spring:
#  application:
#    name: CONFIG-SERVER
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/sreejith-a-nair/cloud-config
#          clone-on-start: true
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
>>>>>>> c80729fd376a6f3205f7ec27885c5e6da6afdf20
